name:                GoogleSheetsDemo
version:             0.1.0.0
github:              "githubuser/GoogleSheetsDemo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/GoogleSheetsDemo#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.10.2
- text >= 1.2.3.0
- bytestring >= 0.10.8.2
- http-conduit >= 2.3.1
- http-client >= 0.5.12.1
- http-client-tls >= 0.3.5.3
- http-types >= 0.12.1
- open-browser >= 0.2.1.0
- aeson >= 1.2.4.0
- yaml >= 0.8.30

library:
  source-dirs: src

executables:
  GoogleSheetsDemo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GoogleSheetsDemo

tests:
  GoogleSheetsDemo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GoogleSheetsDemo
